### PR TITLE
Update deprecated xelatex and lualatex commands

### LINKED ISSUE #18: Undefined control sequence when building with pdflatex
Hi,

When following instructions (cloning repo in `local` and setting `\usepackage{coloremoji}` at top of my .tex file) im getting following error:
```
[LaTeX] Undefined control sequence \u-document-127920 #1->{\coloremoji                                      {🎰}} l.151             \end{frame}
```

I build with `pdflatex`*2

Thanks!

### PR DESCRIPTION
**Pull request by tuvokian**
Fixes #18 #14 #19

### CODE REVIEW

**Comment by asinghvi17** [comment]
bump, @alecjacobson

**Comment by cshaa** [comment]
The pull request doesn't work on my machine 😕
elementary 5.1 (based on Ubuntu 18.04.3 LTS)
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)

[Log here.](https://gist.github.com/m93a/6e1457de834454974e22fbb2162a0125)

image


I tried putting [this definition](https://tex.stackexchange.com/a/195460/51512) before `\usepackage{coloremoji}`, but it failed with
```
Invalid code (1209475), should be in the range 0..1114111.
Package newunicodechar Error: ASCII character requested.
```

**Comment by tmalsburg** [comment]
This PR solves my problem reported in #19.  @m93a are you sure your problem above is related to this PR?

**Comment by shivams** [comment]
This PR doesn't fix #18.

**Pull request closed without merging**
